// ─── Setup ───────────────────────────────────────────────────────────────────
// Before deploying, set these Script Properties in Apps Script:
//   Project Settings → Script Properties → Add property
//
//   MY_NAME         — your full name as it appears in emails, e.g. "Jane Smith"
//   MY_EMAIL        — your full email address, e.g. "jane@example.com"
//   GEMINI_API_KEY  — your Gemini API key
//   DAYS_BACK       — (optional) how many days of email to scan, default 1
//   GMAIL_LABEL     — (optional) label applied to processed threads, default "FocusFlow-Processed"
//   EXTRA_FILTERS   — (optional) space-separated Gmail query tokens to add, e.g. "-label:internal -from:noreply@someservice.com"

// ─── Config ───────────────────────────────────────────────────────────────────
const PROPS = PropertiesService.getScriptProperties();

// ─── HTTP entry point ─────────────────────────────────────────────────────────
function doGet(e) {
  const action   = e.parameter.action;
  const name     = e.parameter.name || PROPS.getProperty("MY_NAME") || "";
  // Priority: URL param → Script Property → hardcoded fallback
  const daysBack = e.parameter.daysBack || PROPS.getProperty("DAYS_BACK") || "1";

  if (action === "pollEmails") {
    const logs = pollAllEmails(name, daysBack);
    return ContentService.createTextOutput(logs)
                         .setMimeType(ContentService.MimeType.TEXT);
  }

  return ContentService.createTextOutput(JSON.stringify({ error: "Invalid action" }))
                       .setMimeType(ContentService.MimeType.JSON);
}

// ─── File helpers ─────────────────────────────────────────────────────────────

/**
 * Returns the Drive File object for tasks.json, creating it (with an empty
 * JSON array) if it doesn't exist yet.
 */
function getTasksFile() {
  const fileName = "tasks.json";
  const files = DriveApp.getFilesByName(fileName);
  if (files.hasNext()) {
    return files.next();
  }
  // Bootstrap: write an empty JSON array so JSONDecoder never sees a blank file.
  return DriveApp.createFile(fileName, "[]", MimeType.PLAIN_TEXT);
}

/**
 * Reads tasks.json and returns a parsed JS array.
 * Falls back to [] on any parse error so a corrupted file doesn't block the script.
 */
function readTasks(file) {
  try {
    const raw = file.getBlob().getDataAsString();
    return JSON.parse(raw);           // always an array
  } catch (err) {
    console.error("Could not parse tasks.json, starting fresh: " + err.message);
    return [];
  }
}

/**
 * Serialises the tasks array back to tasks.json.
 * Uses a 2-space indent so the file is human-readable on Drive.
 */
function writeTasks(file, tasks) {
  file.setContent(JSON.stringify(tasks, null, 2));
}

// ─── Note helpers ─────────────────────────────────────────────────────────────

/**
 * Returns the FocusFlow/notes folder on Drive, creating the hierarchy if needed.
 * Layout: My Drive → FocusFlow → notes
 */
function getFocusFlowNotesFolder() {
  let focusFlowFolder;
  const ffFolders = DriveApp.getFoldersByName("FocusFlow");
  if (ffFolders.hasNext()) {
    focusFlowFolder = ffFolders.next();
  } else {
    focusFlowFolder = DriveApp.createFolder("FocusFlow");
    console.log("Created Drive folder: FocusFlow");
  }

  let notesFolder;
  const nFolders = focusFlowFolder.getFoldersByName("notes");
  if (nFolders.hasNext()) {
    notesFolder = nFolders.next();
  } else {
    notesFolder = focusFlowFolder.createFolder("notes");
    console.log("Created Drive folder: FocusFlow/notes");
  }

  return notesFolder;
}

/**
 * Stamps a markdown note file for a newly created task.
 * File: FocusFlow/notes/<task.id>.md
 * Written once at creation — never overwritten by subsequent polls.
 *
 * @param {Object} task    - The task object just pushed to tasks.json
 * @param {string} subject - Email subject that triggered the task
 * @param {string} body    - Plain-text email body (already truncated to 5000 chars)
 */
function createTaskNote(task, subject, body) {
  try {
    const notesFolder = getFocusFlowNotesFolder();

    // Skip if a note already exists (idempotent — safe to call more than once).
    const existing = notesFolder.getFilesByName(task.id + ".md");
    if (existing.hasNext()) {
      console.log("Note already exists for: " + task.id);
      return;
    }

    // Trim body to a readable excerpt (first 400 chars).
    const excerpt = (body.length > 400 ? body.substring(0, 400).trimEnd() + "…" : body).trim();

    const content = [
      "# " + task.title,
      "",
      "## Source Email",
      "**Subject**: " + subject,
      "**Date**: " + task.date,
      "**Link**: " + (task.link || "—"),
      "",
      "> " + excerpt.split("\n").join("\n> "),
      "",
      "---",
      "",
      "## Notes",
      "",
      "*Add your notes here…*",
      "",
      "---",
      "*Auto-generated by FocusFlow · " + task.date + "*"
    ].join("\n");

    notesFolder.createFile(task.id + ".md", content, MimeType.PLAIN_TEXT);
    console.log("Created note: " + task.id + ".md");
  } catch (err) {
    // Non-fatal: log and continue — the task was already saved.
    console.error("createTaskNote error: " + err.message);
  }
}

// ─── Main polling function ────────────────────────────────────────────────────

function pollAllEmails(targetName, daysBack) {
  if (!targetName) targetName = PROPS.getProperty("MY_NAME") || "";
  if (!daysBack)   daysBack   = PROPS.getProperty("DAYS_BACK") || "1";

  let logs = "Starting poll for all emails...\n";
  console.log("pollAllEmails — name: " + targetName + ", daysBack: " + daysBack);

  targetName = decodeURIComponent(targetName);

  const file  = getTasksFile();
  const tasks = readTasks(file);          // ← JS array of task objects
  const initialCount = tasks.length;

  // Ensure the FocusFlow-Processed label exists (name is configurable via Script Properties).
  const labelName = PROPS.getProperty("GMAIL_LABEL") || "FocusFlow-Processed";
  let label = GmailApp.getUserLabelByName(labelName);
  if (!label) {
    label = GmailApp.createLabel(labelName);
    console.log("Created label: " + labelName);
  }

  // Name/email tokens used to match explicit mentions in mailing-list threads.
  // Loaded from Script Properties — never hardcoded in source.
  const MY_NAME  = PROPS.getProperty("MY_NAME")  || "";
  const MY_EMAIL = PROPS.getProperty("MY_EMAIL") || ""; // full address, e.g. jane@example.com

  // EXTRA_FILTERS: optional org-specific tokens (e.g. "-label:internal -from:noreply@someservice.com").
  const extraFilters = (PROPS.getProperty("EXTRA_FILTERS") || "").trim();

  const query = [
    "-label:" + labelName,
    "-category:promotions",
    "-category:social",
    "-category:updates",
    "-unsubscribe",
    "-is:draft",
    // Block Google Calendar auto-notifications
    "-from:calendar-notification@google.com",
    "-from:calendar-noreply@google.com",
    // Never process emails you wrote yourself (meeting notes, sent mail, etc.)
    "-from:me",
    // Catch emails sent directly to you OR list emails that name you explicitly.
    // Pure list threads with no mention of you are excluded here; the strict
    // Gemini prompt is the second line of defence for anything that slips through.
    "(to:me OR cc:me OR \"" + MY_NAME + "\" OR \"" + MY_EMAIL + "\")",
    extraFilters,
    "newer_than:" + daysBack + "d"
  ].filter(Boolean).join(" ");

  console.log("Gmail query: " + query);
  logs += "Using query: " + query + "\n";

  const threads = GmailApp.search(query, 0, 10);
  console.log("Found " + threads.length + " threads.");
  logs += "Threads found: " + threads.length + "\n";

  // Subject prefixes that signal a calendar invite / RSVP — never actionable tasks.
  const CALENDAR_PREFIXES = [
    "accepted:",
    "declined:",
    "tentatively accepted:",
    "invitation:",
    "canceled:",
    "canceled event:",
    "updated invitation:",
    "updated event:",
    "proposed new time:"
  ];

  threads.forEach(function(thread, index) {
    const subject = thread.getFirstMessageSubject();
    console.log("[" + index + "] " + subject);

    // Case-insensitive prefix check — calendar subjects vary capitalisation.
    const subjectLower = subject.toLowerCase();
    const isCalendarEmail = CALENDAR_PREFIXES.some(function(prefix) {
      return subjectLower.startsWith(prefix);
    });
    if (isCalendarEmail) {
      console.log("  → Skipping calendar email: " + subject);
      logs += "Skipped (calendar): " + subject + "\n";
      // Still label it so we don't re-process next run.
      thread.addLabel(label);
      return;
    }

    logs += "Processing: " + subject + "\n";

    const messages    = thread.getMessages();
    const lastMessage = messages[messages.length - 1];
    let   body        = lastMessage.getPlainBody();
    const permalink   = thread.getPermalink();

    // "MMM d" matches the date format TaskItem uses (e.g. "Apr 29")
    const dateStr = Utilities.formatDate(
      lastMessage.getDate(),
      Session.getScriptTimeZone(),
      "MMM d"
    );

    if (body.length > 5000) {
      body = body.substring(0, 5000) + "... [truncated]";
    }

    const aiResponse = identifyAndExtractTasks(subject, body, targetName);

    if (aiResponse !== null && aiResponse !== "NO_TASKS") {
      const lines = aiResponse.split("\n");
      lines.forEach(function(line) {
        if (line.trim() === "") return;

        const parts = line.split("|");
        if (parts.length < 5) return;

        const project  = parts[0].trim();
        const title    = parts[1].trim();
        const duration = parts[2].trim();   // string from Gemini, e.g. "30"
        const priority = parts[3].trim();
        const category = parts[4].trim();
        const details  = parts[5] ? parts[5].trim() : null;

        // Build a task object whose keys match TaskItem's CodingKeys exactly.
        // duration must be Int (or null) — NOT a string — so JSONDecoder is happy.
        // project is stored as a top-level field (in addition to the [Project] prefix
        // in title) so Swift can group tasks without parsing the title string.
        const task = {
          id:           Utilities.getUuid(),
          title:        "[" + project + "] " + title,
          project:      project || null,
          details:      details || null,
          link:         permalink || null,
          status:       "needsAction",
          duration:     duration ? parseInt(duration, 10) : null,
          priority:     priority || null,
          category:     category || null,
          date:         dateStr,
          parentTaskId: null
        };

        tasks.push(task);
        // Stamp a source-email note on Drive (once at creation, never overwritten).
        createTaskNote(task, subject, body);
        logs += "Added task: " + task.title + "\n";
        console.log("Added: " + task.title);
      });

      thread.addLabel(label);
    } else if (aiResponse === "NO_TASKS") {
      // Still label the thread so we don't re-process it next run.
      thread.addLabel(label);
      logs += "No tasks in thread.\n";
    }
  });

  const newCount = tasks.length - initialCount;
  if (newCount > 0) {
    writeTasks(file, tasks);
    console.log("tasks.json updated — " + newCount + " new task(s) added (" + tasks.length + " total).");
    logs += "New tasks added: " + newCount + "\n";
  } else {
    console.log("No new tasks — tasks.json unchanged (" + tasks.length + " total).");
  }

  logs += "Poll complete. Total tasks: " + tasks.length + "\n";
  return logs;
}

// ─── Gemini helper ────────────────────────────────────────────────────────────

function identifyAndExtractTasks(subject, body, targetName) {
  try {
    const apiKey = PropertiesService.getScriptProperties().getProperty("GEMINI_API_KEY");
    const url    = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=" + apiKey;

    const prompt = `You are a strict task-extraction assistant.

Your job: decide whether the email below contains an actionable task that is
OWNED by ${targetName} — not just mentioned, not FYI, not a mailing-list
discussion they happen to be subscribed to.

Return "NO_TASKS" (exactly, nothing else) if ANY of these are true:
- ${targetName} is not named in the email AND is not the sole/primary recipient
- The email is a broadcast, newsletter, mailing list, or group discussion
- The email is purely informational (FYI, announcement, status update) with no
  request or follow-up directed at ${targetName}
- The email is a calendar invite / RSVP confirmation
- The action item belongs to someone else and ${targetName} is just CC'd for awareness

Only extract a task when the email EXPLICITLY asks ${targetName} to do something,
or when ${targetName} is clearly the owner of a next step.

If there are tasks, output each on its own line (no bullets, no numbering):
Project | Title | Duration | Priority | Category | Details

Where:
- Project: the shortest recognisable customer or team name — ONE word if possible
  (e.g. "Privia", "Pythian", "Internal", "Clear Channel").
  Do NOT copy the email subject or full meeting title. Never include company
  suffixes like "Health", "Inc", or co-presenter names like "+ Google".
- Title: concise action-oriented title, max 5 words
- Duration: estimated minutes (15, 30, 45, 60, 90, or 120)
- Priority: High, Medium, or Low
- Category: Share, Code, Meeting, Prep, Review, or Other
- Details: one sentence describing what needs to be done

Email Subject: ${subject}
Email Body:
${body}`;

    const payload = {
      contents: { parts: [{ text: prompt }] },
      generationConfig: { temperature: 0.2, maxOutputTokens: 500 }
    };

    const options = {
      method: "post",
      contentType: "application/json",
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };

    const maxRetries = 3;
    let response     = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      response = UrlFetchApp.fetch(url, options);
      const code = response.getResponseCode();

      if (code === 200) break;

      if ((code === 503 || code === 429) && attempt < maxRetries) {
        const waitMs = Math.pow(2, attempt) * 1000;
        console.log("API " + code + " — retry " + (attempt + 1) + " in " + waitMs + "ms");
        Utilities.sleep(waitMs);
      } else {
        console.error("API returned " + code + " — aborting.");
        return null;
      }
    }

    const json = JSON.parse(response.getContentText());
    if (json.candidates && json.candidates[0].content && json.candidates[0].content.parts) {
      return json.candidates[0].content.parts[0].text.trim();
    }

    console.error("Unexpected Gemini response: " + response.getContentText());
    return null;

  } catch (err) {
    console.error("identifyAndExtractTasks error: " + err.message);
    return null;
  }
}
